language: node_js
node_js:
  - '0.10.33'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma jshint'
  - 'npm install' # install npm packages

after_script:
  - 'npm test' # or other command for build, run tests, etc