---
language: node_js
node_js:
  - '4'
  - '5'

before_script:
  - npm install -g phantomjs@1.9.8
  - cp protractor.conf.js.travis protractor.conf.js
  - cp karma.conf.js.travis karma.conf.js
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
